package kotlin;

import kotlin.Result.Failure;
import kotlin.jvm.internal.C7573i;

/* renamed from: kotlin.i */
public final class C47965i {
    /* renamed from: a */
    public static final Object m148906a(Throwable th) {
        C7573i.m23587b(th, "exception");
        return new Failure(th);
    }
}
